### ISSUE TITLE
退出按钮的机制，结合jwt-simple'，应该如何处理

### ISSUE THREAD

**Issue by wwb568109135** [justyeh/justyeh.com#10]
退出按钮的机制，结合jwt-simple'，应该如何处理

**Comment by justyeh** [comment]
清空存储的token，然后跳转到登录页

**Comment by wwb568109135** [comment]
在客户端点击页面的logout按钮，异步调用nodejs服务端的logout按钮，在退出的成功回调函数李返回退出成功的信息给客户端，客户端清掉存储在客户度 的token，使用vuejs的路由定位调整到登陆页面！
