### ISSUE TITLE
提问，在pages文件夹里写的事件绑定全部失效，请问作者知道怎么解决吗

### ISSUE THREAD

**Issue by John4166** [justyeh/justyeh.com#4]
如在pages的index.vue绑定@click事件，在静态化页面中会失效，想来寻求方法

**Comment by justyeh** [comment]
请先确保你的浏览器支持Vue.js，并检查页面是否有报错
我的邮箱justyeh@163.com
也可以将你的代码发送给我

**Comment by justyeh** [comment]
抱歉，在我的项目里面并没有使用`nuxt   generate`，之后我到[Nuxt.js](https://github.com/nuxt/nuxt.js/issues?page=2&q=click&utf8=%E2%9C%93)去看了一下，别人也有这样的问题 [#948](https://github.com/nuxt/nuxt.js/issues/948)、[#959](https://github.com/nuxt/nuxt.js/issues/959)，不过这个问题好像并没有解决办法，期待下一个版本吧

**Comment by gauseen** [comment]
解决了吗？我现在还有这问题啊

**Comment by tangolivesky** [comment]
我也碰到了同样的问题，后来查出来是是路由问题，nuxt的router base配置.  
如果你打包出来的dist文件放在网站的根目录下，则默认就是ok的
但是如果你打包出来的dist文件放在网站子目录下面，比如/static/web/ 下面
则需要配置
  router:{
    base:"/static/web/" 
  }
这样绑定事件就是有效的
