### ISSUE TITLE
您这个部署到阿里云了吗？

### ISSUE THREAD

**Issue by github1586** [justyeh/justyeh.com#5]
您这个部署到阿里云了吗 还是？

**Comment by justyeh** [comment]
不是阿里云，用的是vultr，这是他们的官网：https://www.vultr.com

**Comment by github1586** [comment]
那你是整个目录丢到他们的服务器吗 然后执行build 就可以了吗

**Comment by justyeh** [comment]
具体的可以参考这个[http://justyeh.com/post/29](http://justyeh.com/post/29)，在文章最后的**部署**处！
简单说一下：将项目拉到服务器或者pull下来（如果有用git），然后安装安装依赖和打包，最后用pm2让项目在后台跑起来就可以了

**Comment by github1586** [comment]
谢谢
