### ISSUE TITLE
依赖下载完成后执行npm run dev 报错

### ISSUE THREAD

**Issue by sunlianlong** [justyeh/justyeh.com#6]
如题，报错信息：__WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor
截图：
![image](https://user-images.githubusercontent.com/22101668/29449088-fd505f00-842b-11e7-9adf-47b3e0e4c3a8.png)

**Comment by justyeh** [comment]
抱歉，根据你的截图我无法定位错误的位置！

报错是由于在Promise发生了一个错误，但是你没有捕捉。首先你请确认数据库文件的格式和我的是否一致，再之后请检查你的代码里面关于`asyncData`的部分，错误很可能产生于这些地方

**Comment by justyeh** [comment]
抱歉最近没有关注nuxt，今天我去看了下，官方已经将项目升级到了RC6，你的这个报错很多人也遇到了，是由于版本冲突（我的项目基于RC3）导致的。
你可以升级你可以保持现有的版本，但是许多写法就要变了！或者将版本降级为RC3：`npm install --save nuxt@1.0.0-alpha.3`
我更新了README.md，你可以去看看。
