### ISSUE TITLE
关于 pm2部署

### ISSUE THREAD

**Issue by spencer1994** [justyeh/justyeh.com#7]
你好，想请教一下这个nuxt项目怎么用pm2部署，运行了你的那个命令貌似没什么用。

**Comment by justyeh** [comment]
说一下我部署的详细过程：
1 在服务器上安装相关软件：nodejs、pm2、mysql、nginx，并做好配置
2 我将代码发布到了github，然后在服务器上直接pull下来
3 安装相关的依赖：npm install
4 在服务器上构建代码：npm run build
5 让代码在后台运行（方括号表示可选）：pm2 start npm [--name 'your project name'] -- start 

服务器是 Ubuntu 12.04 LTS，
下面是pm2的相关文档：
https://www.npmjs.com/package/pm2
http://pm2.keymetrics.io/docs/usage/quick-start/
https://segmentfault.com/a/1190000002539204

**Comment by spencer1994** [comment]
@justyeh 谢谢你这么细心的解答，但是我直接跑你这个 pm2 start npm [--name 'your project name'] -- start 这个代码会抛错

**Comment by justyeh** [comment]
很显然，`pm2 start npm [--name 'your project name'] -- start `
这个只是一个示例，方括号代表里面的内容是可选的，‘your project name’是代表你可以自定义名称

**Comment by spencer1994** [comment]
@justyeh  pm2 start npm [--name 'your project name'] -- start => pm2 start npm [--name 'test'] -- start，试过改名了。没有用，是否要在当前目录下创建app.js？js中的配置内容配置nuxt的启动服务？

**Comment by spencer1994** [comment]
已解决，需要创建app.js，配置一下即可。新手使用pm2，多谢你的解答！
